stages:
    - build

manuk:build:
    image: rust:1.26
    stage: build
    
    script:
        - cargo build --release --target=x86_64-unknown-linux-gnu
    
    artifacts:
        paths:
            - target/