stages:
    - test

build:linux:
    image: rust:1.26
    stage: test
    
    script:
        - cargo build --release --target=x86_64-unknown-linux-gnu
    
    artifacts:
        paths:
            - target/